#!/bin/bash
#
# Simulates the 'validate' GitHub Actions workflow (validating the YAML data
# files for syntactic and semantic correctness) by running the scripts in the
# 'scripts' directory.
#
# The parallel execution of jobs in GitHub Actions is simulated by running the
# validations sequentially, but always running all of them, even if one fails.
# This allows to see all failed validations in a single run.
#
# Since all scripts in 'scripts' run in Docker containers, the only dependency
# for this pre-commit hook is Docker being installed on the local system.

echo "Running pre-commit hook..."

failed=$(mktemp)

echo "==> Validating schemas..."
scripts/validate-schemas.sh >/dev/null || echo 1 >"$failed"

echo "==> Validating duplicates..."
scripts/validate-duplicates.sh >/dev/null || echo 1 >"$failed"

if [[ -s "$failed" ]]; then
  echo "Aborting commit due to failed pre-commit hook."
  exit 1
else
  exit 0
fi
