name: Validate YAML files
on: [push]
jobs:
  schema:
    name: Schema
    runs-on: ubuntu-latest
    container: weibeld/ajv-cli:5.0.0
    steps:
      - uses: actions/checkout@v3
      - run: scripts/validate-schema.sh
  duplicates:
    name: Duplicates
    runs-on: ubuntu-latest
    container:
      image: mikefarah/yq:4.25.1
      # By default, the container uses the user yq (UID 1000), which has no
      # permissions to write to the directories created by GitHub Actions (such
      # as /__w). This causes the checkout action to fail. Using root (or the
      # user with UID 1001 that is used by GitHub Actions to create these
      # directories) solves this problem.
      options: --user root
    steps:
      - uses: actions/checkout@v3
      - run: scripts/validate-duplicates.sh
