name: Validate YAML files
on: [push]
jobs:
  schema:
    name: Schema
    runs-on: ubuntu-latest
    container: weibeld/ajv-cli:5.0.0
    steps:
      - uses: actions/checkout@v3
      - run: scripts/validate-schema.sh
