name: Validate YAML files
on: [push]
jobs:
  projects:
    name: Projects
    runs-on: ubuntu-latest
    container: weibeld/ajv-cli:5.0.0
    steps:
      - uses: actions/checkout@v3
      - run: ajv --spec draft2020 -c ajv-formats -s schema/projects.json -d schema/test/projects.yaml
  tags:
    name: Tags
    runs-on: ubuntu-latest
    container: weibeld/ajv-cli:5.0.0
    steps:
      - uses: actions/checkout@v3
      - run: ajv --spec draft2020 -c ajv-formats -s schema/tags.json -d tags.yaml
  organisation:
    name: Organisations
    runs-on: ubuntu-latest
    container: weibeld/ajv-cli:5.0.0
    steps:
      - uses: actions/checkout@v3
      - run: ajv --spec draft2020 -c ajv-formats -s schema/organisations.json -d organisations.yaml
